files: ^pose_evaluation/
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.13 # Or the latest stable version
    hooks:
      - id: ruff
        args: [--fix] # This includes formatting and many linting fixes

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: pytest pose_evaluation
        language: system
        types: [python]