name: Lint and Format

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  lint-and-format:
    name: Lint and Format Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Use the latest stable version

      - name: Set up Python
        uses: actions/setup-python@v5 # Use the latest stable version
        with:
          python-version: '3.12' # Specify your Python version

      - name: Install Ruff
        run: pip install ruff

      - name: Run Ruff Checks (Linting)
        run: ruff check .

      - name: Run Ruff Format Check
        # The --check flag makes 'ruff format' exit with a non-zero code if files are not formatted,
        # ensuring the CI pipeline fails.
        run: ruff format pose_evaluation --check